import { existsSync } from "node:fs";
import {
  mkdir,
  mkdtemp,
  readFile,
  rm,
} from "node:fs/promises";
import { createServer, type Server } from "node:http";
import type { AddressInfo } from "node:net";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import {
  runAudit,
  type AuditReport,
  type FailureCode,
  type SurfaceAuditResult,
} from "../src/audit.js";
import { parseConfigText } from "../src/config.js";
import { writeReports } from "../src/report.js";

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const fixturePath = path.join(
  testDirectory,
  "fixtures",
  "browser-failure-matrix.html",
);
const outputRoot = path.join(testDirectory, "..", ".test-output");
let outputDirectory = "";

async function listen(server: Server): Promise<string> {
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolve);
  });
  const address = server.address() as AddressInfo;
  return `http://127.0.0.1:${address.port}`;
}

async function closeServer(server: Server): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    server.close((error) => (error ? reject(error) : resolve()));
  });
}

function getSurface(
  report: AuditReport,
  surfaceId: string,
): SurfaceAuditResult {
  const surface = report.surfaces.find(
    (candidate) => candidate.surfaceId === surfaceId,
  );
  if (!surface) {
    throw new Error(`Missing browser matrix surface "${surfaceId}".`);
  }
  return surface;
}

function expectOnlyFailure(
  surface: SurfaceAuditResult,
  code: FailureCode,
): void {
  expect(surface.passed).toBe(false);
  expect(surface.failures.map((failure) => failure.code)).toEqual([code]);
}

beforeAll(async () => {
  await mkdir(outputRoot, { recursive: true });
  outputDirectory = await mkdtemp(
    path.join(outputRoot, "browser-failure-matrix-"),
  );
});

afterAll(async () => {
  const resolvedOutput = path.resolve(outputDirectory);
  if (resolvedOutput.startsWith(`${path.resolve(outputRoot)}${path.sep}`)) {
    await rm(resolvedOutput, { recursive: true, force: true });
  }
});

describe("browser assertion expected-failure matrix", () => {
  it("isolates documented browser failures while preserving a passing control and evidence", async () => {
    const fixtureHtml = await readFile(fixturePath, "utf8");
    const server = createServer((request, response) => {
      if (request.url === "/disconnect") {
        request.socket.destroy();
        return;
      }

      const status = request.url === "/http-error" ? 503 : 200;
      response.writeHead(status, {
        "content-type": "text/html; charset=utf-8",
      });
      response.end(fixtureHtml);
    });
    const serverOrigin = await listen(server);

    try {
      const config = parseConfigText(`
version: 1
project:
  name: browser-failure-matrix
browser:
  timeoutMs: 1000
  waitUntil: domcontentloaded
  viewport:
    width: 640
    height: 480
network:
  requestedPrivateOrigins:
    - ${JSON.stringify(serverOrigin)}
output:
  screenshots: true
surfaces:
  - id: passing-control
    target: ${JSON.stringify(fixturePath)}
    disclosures:
      - id: passing-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
  - id: missing-selector
    target: ${JSON.stringify(fixturePath)}
    disclosures:
      - id: missing-disclosure
        selector: "#not-present"
        expectedText: "AI system"
  - id: text-mismatch
    target: ${JSON.stringify(fixturePath)}
    disclosures:
      - id: wrong-copy
        selector: "#text-mismatch-control"
        expectedText: "This response was generated by AI."
  - id: expected-visible
    target: ${JSON.stringify(fixturePath)}
    disclosures:
      - id: unexpectedly-hidden
        selector: "#hidden-control"
        expectedText: "This disclosure should be visible."
        inViewport: false
        unobstructed: false
        accessible: false
  - id: expected-hidden
    target: ${JSON.stringify(fixturePath)}
    disclosures:
      - id: unexpectedly-visible
        selector: "#visible-control"
        expectedText: "This disclosure should be hidden."
        visible: false
  - id: initial-viewport
    target: ${JSON.stringify(fixturePath)}
    disclosures:
      - id: below-fold
        selector: "#below-initial-viewport"
        expectedText: "This response was generated by AI."
        unobstructed: false
  - id: overlay-obstruction
    target: ${JSON.stringify(fixturePath)}
    disclosures:
      - id: covered-disclosure
        selector: "#obstructed-control"
        expectedText: "This response was generated by AI."
  - id: accessible-name
    target: ${JSON.stringify(fixturePath)}
    disclosures:
      - id: wrong-accessible-name
        selector: "#accessible-name-control"
        expectedText: "This response was generated by AI."
        accessibleName: "AI generation notice"
  - id: first-interaction-unavailable
    target: ${JSON.stringify(fixturePath)}
    firstInteraction:
      selector: "#disabled-first-interaction"
      action: focus
    disclosures:
      - id: interaction-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
  - id: readiness-timeout
    target: ${JSON.stringify(fixturePath)}
    waitFor: "#never-ready"
    disclosures:
      - id: ready-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
  - id: http-error
    target: ${JSON.stringify(`${serverOrigin}/http-error`)}
    disclosures:
      - id: http-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
  - id: navigation-error
    target: ${JSON.stringify(`${serverOrigin}/disconnect`)}
    disclosures:
      - id: unreachable-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
`);

      const report = await runAudit(config, {
        baseDirectory: testDirectory,
        outputDirectory,
        mode: "audit",
        trustedPrivateOrigins: [serverOrigin],
      });
      const written = await writeReports(report, outputDirectory, {
        baseDirectory: testDirectory,
      });

      const passingControl = getSurface(report, "passing-control");
      expect(passingControl).toMatchObject({
        passed: true,
        viewport: { width: 640, height: 480 },
        failures: [],
      });
      expect(passingControl.checks).toEqual([
        expect.objectContaining({
          disclosureId: "passing-disclosure",
          passed: true,
          actualVisible: true,
          inViewport: true,
          unobstructed: true,
          accessible: true,
          observationPhase: "initial",
        }),
      ]);
      expect(passingControl.pageContentSha256).toMatch(/^[a-f0-9]{64}$/u);
      expect(passingControl.screenshotSha256).toMatch(/^[a-f0-9]{64}$/u);
      expect(existsSync(passingControl.screenshotPath ?? "")).toBe(true);

      const missingSelector = getSurface(report, "missing-selector");
      expectOnlyFailure(missingSelector, "SELECTOR_NOT_FOUND");
      expect(missingSelector.checks[0]).toMatchObject({
        matchedElements: 0,
        passed: false,
        failures: [
          expect.objectContaining({
            code: "SELECTOR_NOT_FOUND",
            selector: "#not-present",
          }),
        ],
      });

      const textMismatch = getSurface(report, "text-mismatch");
      expectOnlyFailure(textMismatch, "TEXT_MISMATCH");
      expect(textMismatch.checks[0]).toMatchObject({
        actualText: "This is unrelated product copy.",
        actualVisible: true,
        passed: false,
        failures: [
          expect.objectContaining({
            code: "TEXT_MISMATCH",
            expected: "This response was generated by AI.",
            actual: "This is unrelated product copy.",
          }),
        ],
      });

      const expectedVisible = getSurface(report, "expected-visible");
      expectOnlyFailure(expectedVisible, "VISIBILITY_MISMATCH");
      expect(expectedVisible.checks[0]).toMatchObject({
        expectedVisible: true,
        actualVisible: false,
        failures: [
          expect.objectContaining({
            code: "VISIBILITY_MISMATCH",
            expected: "true",
            actual: "false",
          }),
        ],
      });

      const expectedHidden = getSurface(report, "expected-hidden");
      expectOnlyFailure(expectedHidden, "VISIBILITY_MISMATCH");
      expect(expectedHidden.checks[0]).toMatchObject({
        expectedVisible: false,
        actualVisible: true,
        failures: [
          expect.objectContaining({
            code: "VISIBILITY_MISMATCH",
            expected: "false",
            actual: "true",
          }),
        ],
      });

      const initialViewport = getSurface(report, "initial-viewport");
      expectOnlyFailure(initialViewport, "NOT_IN_VIEWPORT");
      expect(initialViewport.checks[0]).toMatchObject({
        actualVisible: true,
        inViewport: false,
        passed: false,
        failures: [
          expect.objectContaining({ code: "NOT_IN_VIEWPORT" }),
        ],
      });

      const overlayObstruction = getSurface(
        report,
        "overlay-obstruction",
      );
      expectOnlyFailure(overlayObstruction, "OBSTRUCTED");
      expect(overlayObstruction.checks[0]).toMatchObject({
        inViewport: true,
        unobstructed: false,
        coveredBy: "div#overlay-blocker",
        passed: false,
        failures: [
          expect.objectContaining({
            code: "OBSTRUCTED",
            actual: "div#overlay-blocker",
          }),
        ],
      });

      const accessibleName = getSurface(report, "accessible-name");
      expectOnlyFailure(accessibleName, "ACCESSIBILITY_MISMATCH");
      expect(accessibleName.checks[0]).toMatchObject({
        accessible: true,
        accessibleName: "Generic disclosure",
        passed: false,
        failures: [
          expect.objectContaining({
            code: "ACCESSIBILITY_MISMATCH",
            expected: "AI generation notice",
            actual: "Generic disclosure",
          }),
        ],
      });

      const firstInteraction = getSurface(
        report,
        "first-interaction-unavailable",
      );
      expectOnlyFailure(firstInteraction, "FIRST_INTERACTION_UNAVAILABLE");
      expect(firstInteraction.checks[0]?.passed).toBe(true);
      expect(firstInteraction.firstInteraction).toMatchObject({
        selector: "#disabled-first-interaction",
        matchedElements: 1,
        visible: true,
        enabled: false,
        passed: false,
      });

      const readinessTimeout = getSurface(report, "readiness-timeout");
      expectOnlyFailure(readinessTimeout, "WAIT_FOR_FAILED");
      expect(readinessTimeout.checks[0]?.passed).toBe(true);
      expect(readinessTimeout.failures[0]).toMatchObject({
        code: "WAIT_FOR_FAILED",
        selector: "#never-ready",
      });

      const httpError = getSurface(report, "http-error");
      expectOnlyFailure(httpError, "HTTP_ERROR");
      expect(httpError).toMatchObject({
        httpStatus: 503,
        finalUrl: `${serverOrigin}/http-error`,
      });
      expect(httpError.checks[0]?.passed).toBe(true);

      const navigationError = getSurface(report, "navigation-error");
      expectOnlyFailure(navigationError, "NAVIGATION_FAILED");
      expect(navigationError).toMatchObject({
        finalUrl: null,
        httpStatus: null,
        checks: [],
      });

      expect(report).toMatchObject({
        passed: false,
        summary: {
          totalSurfaces: 12,
          passedSurfaces: 1,
          failedSurfaces: 11,
          totalChecks: 11,
          passedChecks: 4,
          failedChecks: 7,
          totalFailures: 11,
        },
      });
      expect(existsSync(written.jsonPath)).toBe(true);
      expect(existsSync(written.htmlPath)).toBe(true);

      const jsonText = await readFile(written.jsonPath, "utf8");
      const html = await readFile(written.htmlPath, "utf8");
      const persisted = JSON.parse(jsonText) as AuditReport;
      expect(persisted.summary).toEqual(report.summary);
      expect(persisted.surfaces).toHaveLength(12);
      for (const code of [
        "SELECTOR_NOT_FOUND",
        "TEXT_MISMATCH",
        "VISIBILITY_MISMATCH",
        "NOT_IN_VIEWPORT",
        "OBSTRUCTED",
        "ACCESSIBILITY_MISMATCH",
        "FIRST_INTERACTION_UNAVAILABLE",
        "WAIT_FOR_FAILED",
        "HTTP_ERROR",
        "NAVIGATION_FAILED",
      ] satisfies FailureCode[]) {
        expect(jsonText).toContain(`"${code}"`);
        expect(html).toContain(code);
      }
    } finally {
      await closeServer(server);
    }
  }, 60_000);
});
