import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import {
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { createServer, type Server } from "node:http";
import type { AddressInfo } from "node:net";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { AuditReport, FailureCode } from "../src/audit.js";

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(testDirectory, "..");
const cliPath = path.join(repositoryRoot, "dist", "cli.js");
const fixturePath = path.join(
  testDirectory,
  "fixtures",
  "browser-failure-matrix.html",
);
const outputRoot = path.join(repositoryRoot, ".test-output");
let temporaryDirectory = "";

interface CliResult {
  exitCode: number | null;
  signal: NodeJS.Signals | null;
  stderr: string;
  stdout: string;
}

async function listen(server: Server): Promise<string> {
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolve);
  });
  const address = server.address() as AddressInfo;
  return `http://127.0.0.1:${address.port}`;
}

async function closeServer(server: Server): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    server.close((error) => (error ? reject(error) : resolve()));
  });
}

async function runCli(arguments_: string[]): Promise<CliResult> {
  return await new Promise<CliResult>((resolve, reject) => {
    const child = spawn(process.execPath, [cliPath, ...arguments_], {
      cwd: repositoryRoot,
      env: {
        ...process.env,
        NO_COLOR: "1",
      },
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });
    let stdout = "";
    let stderr = "";
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk: string) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk: string) => {
      stderr += chunk;
    });
    child.once("error", reject);
    child.once("close", (exitCode, signal) => {
      resolve({ exitCode, signal, stderr, stdout });
    });
  });
}

beforeAll(async () => {
  await mkdir(outputRoot, { recursive: true });
  temporaryDirectory = await mkdtemp(
    path.join(outputRoot, "cli-failure-matrix-"),
  );
});

afterAll(async () => {
  const resolvedTemporaryDirectory = path.resolve(temporaryDirectory);
  if (
    resolvedTemporaryDirectory.startsWith(
      `${path.resolve(outputRoot)}${path.sep}`,
    )
  ) {
    await rm(resolvedTemporaryDirectory, { recursive: true, force: true });
  }
});

describe("published CLI entrypoint failure matrix", () => {
  it("returns exit 1 and retains every browser pass/failure observation", async () => {
    expect(existsSync(cliPath)).toBe(true);
    const fixtureHtml = await readFile(fixturePath, "utf8");
    const server = createServer((request, response) => {
      if (request.url === "/disconnect") {
        request.socket.destroy();
        return;
      }

      const status = request.url === "/http-error" ? 503 : 200;
      response.writeHead(status, {
        "content-type": "text/html; charset=utf-8",
      });
      response.end(fixtureHtml);
    });
    const serverOrigin = await listen(server);
    const localFixturePath = path.join(temporaryDirectory, "matrix.html");
    const configPath = path.join(temporaryDirectory, "matrix.yml");
    const reportDirectory = path.join(temporaryDirectory, "reports");
    await copyFile(fixturePath, localFixturePath);
    await writeFile(
      configPath,
      `version: 1
project:
  name: published-cli-browser-failure-matrix
browser:
  timeoutMs: 1000
  waitUntil: domcontentloaded
  viewport:
    width: 640
    height: 480
network:
  requestedPrivateOrigins:
    - ${JSON.stringify(serverOrigin)}
output:
  screenshots: true
surfaces:
  - id: passing-control
    target: matrix.html
    disclosures:
      - id: passing-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
  - id: missing-selector
    target: matrix.html
    disclosures:
      - id: missing-disclosure
        selector: "#not-present"
        expectedText: "AI system"
  - id: text-mismatch
    target: matrix.html
    disclosures:
      - id: wrong-copy
        selector: "#text-mismatch-control"
        expectedText: "This response was generated by AI."
  - id: expected-visible
    target: matrix.html
    disclosures:
      - id: unexpectedly-hidden
        selector: "#hidden-control"
        expectedText: "This disclosure should be visible."
        inViewport: false
        unobstructed: false
        accessible: false
  - id: expected-hidden
    target: matrix.html
    disclosures:
      - id: unexpectedly-visible
        selector: "#visible-control"
        expectedText: "This disclosure should be hidden."
        visible: false
  - id: initial-viewport
    target: matrix.html
    disclosures:
      - id: below-fold
        selector: "#below-initial-viewport"
        expectedText: "This response was generated by AI."
        unobstructed: false
  - id: overlay-obstruction
    target: matrix.html
    disclosures:
      - id: covered-disclosure
        selector: "#obstructed-control"
        expectedText: "This response was generated by AI."
  - id: accessible-name
    target: matrix.html
    disclosures:
      - id: wrong-accessible-name
        selector: "#accessible-name-control"
        expectedText: "This response was generated by AI."
        accessibleName: "AI generation notice"
  - id: first-interaction-unavailable
    target: matrix.html
    firstInteraction:
      selector: "#disabled-first-interaction"
      action: focus
    disclosures:
      - id: interaction-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
  - id: readiness-timeout
    target: matrix.html
    waitFor: "#never-ready"
    disclosures:
      - id: ready-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
  - id: http-error
    target: ${JSON.stringify(`${serverOrigin}/http-error`)}
    disclosures:
      - id: http-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
  - id: navigation-error
    target: ${JSON.stringify(`${serverOrigin}/disconnect`)}
    disclosures:
      - id: unreachable-disclosure
        selector: "#passing-control"
        expectedText: "interacting with an AI system"
`,
      "utf8",
    );

    try {
      const result = await runCli([
        "audit",
        "--config",
        configPath,
        "--output",
        reportDirectory,
        "--allow-private-origin",
        serverOrigin,
      ]);

      expect(result).toMatchObject({
        exitCode: 1,
        signal: null,
        stderr: "",
      });
      expect(result.stdout).toContain("CHECKS FAIL");
      expect(result.stdout).toContain("11 failures");

      const reportNames = await readdir(reportDirectory);
      const jsonName = reportNames.find((name) => name.endsWith(".json"));
      const htmlName = reportNames.find((name) => name.endsWith(".html"));
      expect(jsonName).toBeDefined();
      expect(htmlName).toBeDefined();
      const jsonText = await readFile(
        path.join(reportDirectory, jsonName!),
        "utf8",
      );
      const htmlText = await readFile(
        path.join(reportDirectory, htmlName!),
        "utf8",
      );
      const report = JSON.parse(jsonText) as AuditReport;

      expect(report).toMatchObject({
        schemaVersion: 2,
        passed: false,
        mode: "audit",
        project: "published-cli-browser-failure-matrix",
        tool: {
          name: "art50-ci",
          version: "0.4.0",
        },
        summary: {
          totalSurfaces: 12,
          passedSurfaces: 1,
          failedSurfaces: 11,
          totalChecks: 11,
          passedChecks: 4,
          failedChecks: 7,
          totalFailures: 11,
        },
      });
      const failureCodes = report.surfaces.flatMap((surface) =>
        surface.failures.map((failure) => failure.code),
      );
      for (const code of [
        "SELECTOR_NOT_FOUND",
        "TEXT_MISMATCH",
        "VISIBILITY_MISMATCH",
        "NOT_IN_VIEWPORT",
        "OBSTRUCTED",
        "ACCESSIBILITY_MISMATCH",
        "FIRST_INTERACTION_UNAVAILABLE",
        "WAIT_FOR_FAILED",
        "HTTP_ERROR",
        "NAVIGATION_FAILED",
      ] satisfies FailureCode[]) {
        expect(failureCodes).toContain(code);
        expect(jsonText).toContain(`"${code}"`);
        expect(htmlText).toContain(code);
      }
      expect(
        report.surfaces.every(
          (surface) =>
            surface.screenshotPath !== null &&
            /^[a-f0-9]{64}$/u.test(surface.screenshotSha256 ?? "") &&
            existsSync(
              path.resolve(reportDirectory, surface.screenshotPath),
            ),
        ),
      ).toBe(true);
    } finally {
      await closeServer(server);
    }
  }, 60_000);
});
